
[project]
name = "clarity-mainnet-contracts"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "SP3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSQP2HGT6.operable"
[[project.requirements]]
contract_id = "SP3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSQP2HGT6.transferable"

[contracts.crashpunks-v2]
path = "contracts/SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ/crashpunks-v2.clar"
depends_on = ["crashpunks-v1", "commission-trait"]

[contracts.crashpunks-v1]
path = "contracts/SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ/crashpunks-v1.clar"
depends_on = []


[contracts.commission-trait]
path = "contracts/SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ/commission-trait.clar"
depends_on = []
