name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
  
      - name: get contracts
        run: |
          yarn start

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add new contracts
