name: Add new contracts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  get-contracts:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: get contracts
        run: |
          yarn
          yarn start

      - name: commit main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add new contracts
          branch: main
          file_pattern: contracts *.txt
      - name: Checkout docs
        run: |
          git checkout docs --
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
          git pull
          git merge --no-ff main -m "Auto-merge main to docs"
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add new documentation
          branch: docs
