name: Add new contracts manually
on: workflow_dispatch
jobs:
  get-contracts:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: get contracts
        run: |
          yarn
          yarn start

      - name: commit main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add new contracts
          branch: main
          file_pattern: contracts *.txt
      - name: Checkout docs
        run: |
          git checkout docs --
      - name: Merge main
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: main
          # Branch that will be updated
          branch: docs
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add new documentation
          branch: docs
